### ISSUE TITLE
plugin crash

### ISSUE THREAD

**Issue by druppy** [Phaiax/ArcticTypescript#12] opened 2015-01-13 09:10 UTC
Hi ...

Sometimes i get this error, popup from sublime : 

"plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted"

Are there anything I can do to clarify what kind of error this is all about ?

**Comment by Phaiax** [comment] 2015-01-13 10:29
Hey druppy.

Can you open up the console "View -> Show Console" after the error happened and provide the error which appeared there?

Which OS and sublime version are you using?

- Phaiax

**Comment by druppy** [comment] 2015-01-13 12:20
Debian linux 64 (Jessie) Sublime text 3 (3066 : Dev)

the console keep saying : 
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 271, in on_modified
    callback.on_modified(v)
  File "vcs_gutter_events in /home/bl/.config/sublime-text-3/Installed Packages/VCS Gutter.sublime-package", line 46, in on_modified
  File "view_collection in /home/bl/.config/sublime-text-3/Installed Packages/VCS Gutter.sublime-package", line 33, in add
  File "vcs_helpers in /home/bl/.config/sublime-text-3/Installed Packages/VCS Gutter.sublime-package", line 65, in is_git_repository
  File "vcs_helpers in /home/bl/.config/sublime-text-3/Installed Packages/VCS Gutter.sublime-package", line 52, in is_repository
  File "vcs_helpers in /home/bl/.config/sublime-text-3/Installed Packages/VCS Gutter.sublime-package", line 47, in vcs_tree
  File "./posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 271, in on_modified
    callback.on_modified(v)
  File "vcs_gutter_events in /home/bl/.config/sublime-text-3/Installed Packages/VCS Gutter.sublime-package", line 46, in on_modified
  File "view_collection in /home/bl/.config/sublime-text-3/Installed Packages/VCS Gutter.sublime-package", line 33, in add
  File "vcs_helpers in /home/bl/.config/sublime-text-3/Installed Packages/VCS Gutter.sublime-package", line 65, in is_git_repository
  File "vcs_helpers in /home/bl/.config/sublime-text-3/Installed Packages/VCS Gutter.sublime-package", line 52, in is_repository
  File "vcs_helpers in /home/bl/.config/sublime-text-3/Installed Packages/VCS Gutter.sublime-package", line 47, in vcs_tree
  File "./posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
```
I hope that helps just a bit.

It seems like the plugin gives up after a given number of unhandled exceptions.

**Comment by Phaiax** [comment] 2015-01-14 17:00
This is a bug in VcsGutter which is caused by the special windows of ArcticTypescript. I have reported it here: https://github.com/bradsokol/VcsGutter/issues/31

But I don't know when and if it will be fixed.

**Closed by Phaiax** 2015-01-14 17:00 UTC
